package com.farhan.mengenaldinosaurus

object DinosData {
    private val dinoNames = arrayOf("Ankylosaurus",
                                    "Apatosaurus",
                                    "Archaeopteryx",
                                    "Brachiosaurus",
                                    "Compsognathus",
                                    "Megalosaurus",
                                    "Spinosaurus",
                                    "Stegosaurus",
                                    "Triceratops",
                                    "Tyrannosaurus Rex",
                                    "Velociraptor"

    )

    private val dinoDetail = arrayOf("Ankylosaurus adalah salah satu jenis dinosaurus yang hidup pada periode kapur akhir sekitar 68 juta hingga 65 juta tahun yang lalu di Amerika Utara. Memiliki tubuh sepanjang 8 meter ( 26 kaki), tingginya sekitar 2 meter ( 6.6 kaki), dan beratnya mencapai setidaknya 4 ton.  \n\nAnkylosaurus memiliki tubuh yang dilindungi oleh semacam cangkang keras yang membuat tubuhnya tidak bisa diserang dengan mudah, bahkan oleh Tyrannosaurus rex. Perisai tulang setebal 5 cm melindungi tubuhnya yang pendek, yang disangga oleh empat kakinya yang kuat, pendek dan gemuk. Di ekornya terdapat bola dari batu seberat 5 kg. Jika Ankylosaurus dihadang oleh lawannya, ia akan menyerang lawan tersebut dengan ekor kerasnya dan dalam sekejap lawannya akan terjatuh. Para ilmuwan dan ahli palaeontologi biasanya menyebut Ankylosaurus dengan sebutan 'Anky kecil'.",
            "Apatosaurus (Pelafalan Inggris: /əˌpætəˈsɔːrəs/; yang berarti \"kadal kilat\" dari bahasa Yunani brontē/βροντη artinya 'kilat' dan sauros/σαυρος artinya 'kadal'), adalah sebuah genus dinosaurus sauropoda yang sudah tidak dipakai lagi. Othniel Charles Marsh mendeskripsikan dan menamakan spesies pertama yang diketahui, A. ajax, pada 1877, dan spesies kedua, A. louisae, ditemukan dan dinamakan oleh William H. Holland pada 1916. \n\nApatosaurus hidup sekitar 152 sampai 151 juta tahun yang lalu (mya), selama zaman Kimmeridgium sampai Tithonium awal, dan diketahui fosilnya dari Formasi Morrison di Colorado, Oklahoma, New Mexico, Wyoming, dan Utah di Amerika Serikat. Apatosaurus memiliki panjang rata-rata 21–228 m (69–748 ft), dan berbobot rata-rata 164–224 t (161–220 ton panjang; 181–247 ton pendek). Beberapa spesimen menunjukkan bahwa panjang maksimum 11–30% lebih besar dari rata-rata dan berbobot 327–726 t (322–715 ton panjang; 360–800 ton pendek). \n\nMemiliki ekor panjang sebagai cambuk mematikan. Selain itu musuh utamanya adalah karnivora besar seperti Allosaurus. Habitatnya biasanya di tepi danau dan di hutan. Meskipun nama Brontosaurus diganti kembali menjadi Apatosaurus. Penelitian pada tahun 2015 mengungkapkan terdapat perbedaan antara Brontosaurus dengan Apatosaurus, bahwa Apatosaurus lebih masif dan kuat dengan leher yang lebih tebal dari Brontosaurus.[5] Diperkirakan Apatosaurus mempunyai panjang (yang diukur dari ujung kepala ke ujung ekor) mencapai 27,4 meter.",
            "Archaeopteryx (/ˌɑːrkiːˈɒptərɪks/; terj. har. sayap tua, dari Bahasa Yunani Kuno ἀρχαῖος archaios yang berarti 'kuno' dan πτέρυξ pteryx yang bearti 'bulu unggas' atau 'sayap') adalah jenis burung paling awal dan primitif yang diketahui.[2] Binatang ini hidup pada Periode Jura sekitar 155–150 juta tahun lalu yang saat ini dikenal sebagai wilayah Jerman bagian selatan.[3] Dalam Bahasa Jerman, Archaeopteryx dikenal sebagai Urvogel, sebuah kata yang berarti \"burung yang asli\" atau \"burung pertama\". Meskipun namanya yang asli berasal dari Bahasa Jerman, Kata ini juga digunakan dalam Bahasa Inggris. \n\nBurung modern adalah salah satu keturunan dari spesies ini, burung adalah salah satu spesies dari klad dinosauria yang masih hidup sampai saat ini. Sejak fosil Archaeopteryx ditemukan pertama kali di Jerman tahun 1861, spesies ini sempat membuat bingung para ilmuwan. 1861 merupakan waktu dua tahun, setelah Charles Darwin mempublikasikan temuan itu dalam jurnal On The Origin of Species. \n\nDengan cakar dan gigi yang mirip dengan dinosaurus, Archaeopteryx juga memiliki bulu layaknya seekor burung. Ini membuktikan teori Darwin dalam jurnal itu yang menyebutkan bahwa dinosaurus merupakan cikal bakal burung. Archaeopteryx merupakan transisi dari dinosaurus menjadi burung. Darwin menyebutnya sebagai Urvoger, dari bahasa Jerman yang berarti 'Burung Pertama'. Meskipun bukti burung dinosaurus belum muncul hingga sekarang, banyak ilmuwan yang percaya bahwa Archaeopteryx merupakan dinosaurus pertama yang mampu terbang. Spesimen fosil yang berjumlah 11 itu dipublikasikan pertama kali pada 2011 dan masih dalam keadaan baik. Spesimen tersebut, dilengkapi dengan impresi bulu di seluruh tulang. Bulu-bulu tersebut, berukuran panjang dan simetris di bagian atas kaki. Namun, sampai di bagian bawah, ukurannya semakin pendek. Para peneliti menggambarkan 'celana' bulu ini sebagai penutup diri, alat kamuflase, mengisolasi diri bahkan alat manuver saat berada di bawah. \"Memang tidak dirancang untuk membantu terbang, tetapi cukup membantu saat melakukan pendaratan, mirip dengan bulu burung elang dan sejenisnya,\" ujar Dr. Oliver Rauhut dari Bavarian State Collection untuk Palaeontologi dan Geologi. Menurut Dr. Rauhut, bulu-bulu ini menunjukkan poros yang kuat. Ini merupakan bukti jika burung generasi pertama ini bisa terbang.",
            "Brachiosaurus (Pelafalan Inggris: /ˌbrækiəˈsɔːrəs/) adalah genus dinosaurus sauropoda yang hidup di Amerika Utara selama Jura Akhir, sekitar 154 - 150 juta tahun yang lalu.[2] Dinosaurus ini pertama kali dijelaskan oleh paleontolog Amerika bernama Elmer S. Riggs pada tahun 1903 dari fosil-fosil yang ditemukan di lembah Sungai Colorado di Colorado barat, Amerika Serikat. Riggs menamai dinosaurus ini Brachiosaurus altithorax; nama generiknya adalah bahasa Yunani untuk \"kadal lengan\", dikarenakan proporsi lengannya yang panjang, dan nama spesifik berarti \"dada dalam\". Panjang Brachiosaurus diperkirakan antara 18 dan 26 meter (59 dan 85 kaki); bobotnya diperkirakan mencapai 28.3 sampai 58 ton metrik (31.2 and 64 ton pendek). Dinosaurus ini memiliki leher panjang yang tidak proporsional, tengkorak kecil, dan berukuran besar secara keseluruhan, yang merupakan ciri-ciri khas sauropoda. Ciri Brachiosaurus yang bukan merupakan ciri khas sebagian besar sauropoda adalah kaki depan yang lebih panjang daripada kaki belakang, yang membuat badan yang cenderung curam, dan ekor yang lebih pendek secara proporsional. \n\nNama genus Brachiosaurus menjadi asal nama famili Brachiosauridae, yang mengandung beberapa sauropoda lainnya yang mirip dengan Brachiosaurus. Faktanya, penggambaran Brachiosaurus yang paling populer dibuat berdasarkan Giraffatitan, genus dinosaurus brachiosaurid dari Formasi Tendaguru di Tanzania. Giraffatitan awalnya dijelaskan oleh paleontolog asal Jerman bernama Werner Janensch pada 1914 sebagai spesies Brachiosaurus, B. brancai, namun dipindahkan ke genusnya sendiri pada tahun 2009. Tiga spesies Brachiosaurus lainnya dinamai berdasarkan fosil-fosil yang ditemukan di Afrika dan Eropa; keduanya tidak lagi dianggap valid, dan yang ketiga telah menjadi genus terpisah, Lusotitan.",
            "Compsognathus (Pengucapan Inggris: /kɒmpˈsɒɡnəθəs/; Yunani kompsos/κομψός; \"elegan\", \"halus\" atau \"cantik\", and gnathos/γνάθος; \"rahang\")adalah jenis dinosaurus kecil pada periode jura akhir (sekitar 161 juta hingga 146 juta tahun yang lalu) yang menyerang secara berkelompok seperti Velociraptor. Pertama kali ditemukan di Bavaria, Jerman pada tahun 1861 oleh ahli Paleontologi, Joseph Oberndorc. \n\nKelompok Compsognathus jauh lebih banyak daripada Velociraptor, karena tubuh mereka jauh lebih kecil. Strategi kelompok Compsognathus lebih agresif daripada Velociraptor. Mereka tidak menggunakan pengalih perhatian, melainkan bantuan tambahan di belakang mereka yang sudah siap siaga. Compsognathus, Velociraptor, dan Tyrannosaurus memiliki bentuk yang mirip, tetapi mereka memiliki jenis yang berbeda. Dinosaurus ini merupakan dinosaurus yang paling kecil dengan panjang 60 cm dan hanya sebesar ayam. Hidup pada zaman Jurassic akhir sampai dengan awal Cretaceous.",
            "Megalosaurus Dari Bahasa Yunani dan Latin,Mega=Besar/hebat/raksasa dan Sauros=Kadal,merupakan salah satu jenis dinosaurus pertama yang ditemukan,walau saat pertama ditemukan Megalosaurus belum dikenali sebagai dinosaurus dan rekonstruksinya masih jauh berbeda.Megalosaurus merupakan dinosaurus karnivora terbesar pada periode Pertengahan Jurasik. \n\nMegalosaurus sama seperti dinosaurus Theropoda pada umumnya,dengan tubuh yang besar,rahang dan leher yang kuat dan kokoh, gigi tajam dan bergerigi,berjalan dengan dua kaki,dan memiliki lengan yang tidak terlalu besar dengan empat jari bercakar,serta ekor yang panjang dan kuat.Ukuran Megalosaurus bervariasi,namun dapat dikatakan mereka tumbuh hingga 9 m (pada beberapa fosil,walau kurang akurat,dikatakan mereka dapat tumbuh hingga 10,5 m) dengan tinggi 3,7 m dan berat 3-3,5 ton.",
            "Spinosaurus (Dari Bahasa Yunani, Spino= Tulang belakang atau duri, dan Sauros= kadal)merupakan dinosaurus terbesar dari anggota Spinosaurida. Spinosaurus juga merupakan satu dari tiga Theropoda terbesar sepanjang masa, yang hidup di daerah yang kini bisa dikenali sebagai Afrika bagian Utara. Spinosaurus cukup terkenal saat ini, karena ukurannya mengalahkan spinosaurus dan Mapusaurus. \n\nSisa sisa kerangka Spinosaurus ditemukan di Mesir pada tahun 1912 dan diberi nama oleh ahli Paleontologi Jerman bernama Ernst Stromer pada tahun 1915. Sisa sisa Spinosaurus yang asli hancur ketika Perang Dunia II, tetapi sedikit demi sedikit, fosil fosil Spinosaurus kembali ditemukan seiring berjalannya waktu.\n\nSpinosaurus merupakan Theropoda raksasa yang dapat tumbuh hingga 18 m dengan tinggi sekitar 5 m (sampai layarnya) dan berat mencapai 7, 6 ton. Panjang tengkorak Spinosaurus 165 cm dengan seratus gigi-gigi runcing yang lurus sepanjang kira-kira 19 cm. Ciri khas Spinosaurus adalah tulang belakangnya yang meninggi 2 m dan merupakan layar yang dilapisi kulit. Di bawah lapisan kulit keras yang liat tersebut terdapat pembuluh darah yang berguna untuk mengatur suhu tubuh Spinosaurus atau untuk menarik perhatian betina saat musim kawin, karena diperkirakan layar Spinosaurus dapat berubah warna seperti kulit bunglon. Spinosaurus juga mempunyai lubang hidung yang tidak terletak di ujung moncong seperti kebanyakan Theropoda, melainkan di dekat matanya supaya bisa bernapas di permukaan air seperti Buaya.",
            "Stegosaurus (diucapkan /ˈsteg.əˌsɔː.rəs/) artinya \"kadal beratap\", karena sisik besar di punggungnya (bahasa Yunani stego = piring/atap + sauros = kadal) adalah sebuah genus dinosaurus herbivora besar dari Awal Jurassic di Amerika Utara. Spesies ini adalah salah satu jenis dinosaurus yang paling mudah diidentifikasi, karena kedua baris sisik yang saling silang di punggungnya (dasar untuk nama ilmiahnya) dan 2 pasang duri panjang di ekornya (disebut thagomizer). \n\nPaleontologis sempat memperdebatkan bagaimana sisik-sisik di punggung Stegosaurus tersusun. Karena sisik tersebut berada di atas lapisan otot punggung (paleontologis bahkan memperkirakan sisik tersebut memiliki pembuluh darah) maka saat Stegosaurus mati dan memfosil, sisik-sisik tersebut terlepas dan saling bertumpukan. Pendapat pertama mengatakan bahwa sisik Stegosaurus menutupi punggungnya, pendapat kedua mengatakan bahwa sisik-sisik tersebut berdiri tegak dan saling bersebelahan dan pendapat terakhir yang paling disetujui adalah sisik-sisiknya berdiri tegak dengan posisi saling silang. \n\nSatu hal yang sering menimbulkan salah paham mengenai Stegosaurus adalah rongga pada ujung ekornya. Dahulu paleontologis mengira bahwa rongga tersebut berisi otak Stegosaurus, sehingga menimbulkan anggapan bahwa Stegosaurus merupakan dinosaurus yang pintar karena memiliki 2 otak. Belakangan diketahui bahwa anggapan tersebut adalah salah. Stegosaurus bukanlah dinosaurus yang cukup pintar karena otaknya hanya sebesar bola golf dan rongga pada ekor Stegosaurus adalah tempat melekatnya otot-otot ekor yang sangat kuat, yang digunakan sebagai alat pertahanan diri dengan mengayunkan ekor berdurinya sekeras mungkin ke arah penyerangnya. \n\nStegosaurus adalah salah satu dinosaurus paling tenang, namun penyerangnya seperti Allosaurus atau Saurophaganax akan menghadapi pertahanan kuat-lempeng dengan semburat merah(karena darah yang dipompakan ke dalam ruang lempengannya saat merasa terancam), serta ayunan ekor yang sangat berbahaya. Duri ekor Stegosaurus panjangnya dapat mencapai 1 m , dan dapat melubangi pemangsa sampai sedalam 90 cm. Para paleontolog pernah menemukan fosil seekor Allosaurus dengan tulang belakang yang berlubang sepasang, membuktikan bahwa herbivora sekalipun, seperti Stegosaurus, bisa mematikan.",
            "Triceratops (dari bahasa Yunani, artinya \"wajah bertanduk tiga\") merupakan jenis dinosaurus bertanduk tiga yang berbadan besar. Panjangnya bisa mecapai 9 m, tingginya sekitar 3 m dan berat 12 ton. Panggilan pendeknya Tritop. Dinosaurus ini jarang lari ketakutan karena Tyrannosaurus, karena biasanya mereka melindungi diri mereka dengan tanduknya yang tajam. Pernah disebut sebagai dinosaurus ksatria, karena bentuk kombinasi kepala dan tanduknya membuat dirinya seperti seorang ksatria dengan pedang dan tameng. Sebutan ini ada benarnya, karena kulit yang berada pada posisi 'tameng' amatlah keras. Selain itu tanduknya yang tajam mampu membuat lawan ketakutan. \n\nriceratops memiliki tiga tanduk, dua di alisnya dan satu di hidungnya. Panjang tengkoraknya mencapai 2 m. Triceratops memiliki empat kaki kokoh untuk menopang tubuhnya. Beberapa ahli mengatakan Triceratops tidak bisa berlari cepat, tetapi mereka dapat mencapai kecepatan setidaknya 30 km/jam.",
            "Tyrannosaurus adalah sebuah genus dinosaurus teropoda yang tergolong ke dalam klad Coelurosauria. Spesies Tyrannosaurus rex (sering dijuluki T. rex atau T-Rex; \"rex\" berarti \"raja\" dalam bahasa Latin) adalah salah satu teropoda besar yang paling dikenal oleh khalayak luas. Tyrannosaurus hidup di sebuah benua yang dikenal dengan nama Laramidia, yang kini telah berubah menjadi Amerika Utara bagian barat. Tyrannosaurus jauh lebih tersebar daripada hewan-hewan Tyrannosauridae lainnya. Fosil-fosil Tyrannosaurus telah ditemukan di berbagai formasi geologi dari zaman Kapur Akhir sekitar 68 hingga 65 juta tahun yang lalu. Tyrannosaurus merupakan salah satu dinosaurus nonburung terakhir sebelum terjadinya peristiwa kepunahan Kapur–Paleogen. \n\nSeperti hewan-hewan Tyrannosauridae lainnya, Tyrannosaurus adalah seekor karnivora bipedal dengan tengkorak besar yang diseimbangkan oleh ekornya yang berat dan panjang. Tyrannosaurus memiliki tungkai belakang yang kuat dan besar, sementara tungkai depannya pendek dan hanya memiliki dua jari. Spesimen Tyrannosaurus yang paling lengkap memiliki panjang 14 m, tinggi 4 m di bagian panggul (titik tertinggi Tyrannosaurus karena hewan ini tidak dapat berdiri tegak), dan menurut perkiraan yang paling modern mempunyai massa antara 8,4 hingga 14 ton. Meskipun terdapat teropoda-teropoda lain dengan besar tubuh yang dapat menyaingi atau bahkan melebihi Tyrannosaurus rex, Tyrannosaurus masih menjadi salah satu predator darat terbesar yang pernah ditemukan dan diperkirakan memiliki gigitan terkuat di antara semua hewan yang hidup di darat. Di lingkungannya, Tyrannosaurus rex merupakan karnivora terbesar, sehingga kemungkinan besar mereka adalah predator puncak yang memangsa Hadrosauridae, herbivora-herbivora seperti Ceratopsia dan Ankylosauria, dan mungkin juga Sauropoda. Terdapat beberapa ahli yang meyakini bahwa Tyrannosaurus murni adalah seekor pemakan bangkai. Perdebatan mengenai jati diri Tyrannosaurus sebagai predator puncak atau pemakan bangkai merupakan salah satu perdebatan terpanjang dalam ilmu paleontologi. Sebagian besar ahli paleontologi saat ini berpegang pada kesimpulan bahwa Tyrannosaurus adalah seekor predator yang juga memakan bangkai. \n\nSejauh ini telah ditemukan lebih dari 50 spesimen Tyrannosaurus rex, dan beberapa di antaranya hampir lengkap. Jaringan lunak dan protein telah didapati pada paling tidak satu spesimen. Berkat jumlah fosil yang berlimpah, peneliti dapat menyelidiki berbagai aspek biologisnya, termasuk sejarah kehidupan dan biomekanikanya. Perilaku makan, fisiologi, dan kecepatan potensial Tyrannosaurus rex merupakan beberapa subjek yang masih diperdebatkan. Taksonominya juga kontroversial, karena beberapa ilmuwan menganggap Tarbosaurus bataar dari Asia sebagai spesies Tyrannosaurus yang kedua, sementara yang lainnya menganggap Tarbosaurus sebagai genus yang terpisah. Beberapa genera Tyrannosauridae yang lain dari Amerika Utara juga telah disinonimkan dengan Tyrannosaurus.",
            "Velociraptor (arti 'pencuri yang gesit')[1] adalah genus dinosaurus theropoda yang hidup pada periode Kapur Akhir. Berbadan lebih kecil dan biasa hidup berkelompok. Strategi menyerang mereka lebih pintar daripada dinosaurus lainnya. Mereka menggunakan penarik perhatian untuk mengalihkan perhatian mangsa mereka, yang sebenarnya mangsa mereka telah dikepung. \n\nVelociraptor hidup di akhir Zaman Kretasius sekitar 65-71 juta tahun yang lalu. Ia termasuk dalam sub-ordo Dromaeosaurida yang memiliki ukuran tubuh sedang, dengan panjang sekitar 7 kaki (2,5 meter) dan tinggi 3 kaki (1 meter) dan berat sekitar 20-60 pound (10-20 kilogram) . Seperti Dromaeosaurida lainnya, tubuh Velociraptor kemungkinan memiliki bulu. Selain itu, mereka memiliki sebuah cakar besar berbentuk melengkung di tiap kakinya, yang kemungkinan digunakan untuk menusuk atau merobek tubuh korbannya, dan juga menyerangnya dengan kuku kaki yang tajam. \n\nVelociraptor juga termasuk pintar bila dibandingkan dengan dinosurus lainnya, dan hal ini membuat mereka mampu bersaing dengan predator besar lain yang hidup di tempat yang sama. Fosilnya ditemukan di daerah Mongolia, Rusia, dan Cina."
    )

    private val dinoGambar = intArrayOf(R.drawable.ankylosaurus,
        R.drawable.apatosaurus,
        R.drawable.archaeopteryx,
        R.drawable.brachiosaurus,
        R.drawable.compsognathus,
        R.drawable.megalosaurus,
        R.drawable.spinosaurus,
        R.drawable.stegosaurus,
        R.drawable.triceratops,
        R.drawable.tyrannosaurusrex,
        R.drawable.velociraptor,
    )

    private val dinoSuara = intArrayOf(R.raw.ankylosaurus,
        R.raw.apatosaurus,
        R.raw.archaeopteryx,
        R.raw.brachiosaurus,
        R.raw.compsognathus,
        R.raw.megalosaurus,
        R.raw.spinosaurus,
        R.raw.stegosaurus,
        R.raw.triceratops,
        R.raw.tyrannosaurusrex,
        R.raw.velociraptor,
    )

    val listData: ArrayList<Dino>
        get() {
            val list = arrayListOf<Dino>()
            for (position in dinoNames.indices) {
                val dino = Dino()
                dino.name = dinoNames[position]
                dino.detail = dinoDetail[position]
                dino.gambar = dinoGambar[position]
                dino.suara = dinoSuara[position]
                list.add(dino)
            }
            return list
        }
}